- name: install and run nginx
  hosts: web
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
       name: nginx
       state: latest
    - name: Start nginx
      ansible.builtin.service:
       name: httpd
       state: started
       enabled: yes