- name: data types in ansible
  hosts: localhost
  vars:
    Course: DevOps with AWS
    Tools:
      - Linux
      - Shell
      - Ansible
    Experience:
      - Devops: 2.5
      - Docker: 1
      - Teraform: 1
    Realtime: true
  tasks:
  - name: print datatypes
    ansible.builtin.debug:
     msg: "My Course is: {{Course}}, Tools used are : {{Tools}}, comes to Experience : {{Experience}} and I involved in a Realtime project : {{Realtime}} "

# - name: data types
#   hosts: localhost
#   vars:
#     Course: DevOps with AWS #string
#     Tools: # list
#     - Linux
#     - Shell
#     - Ansible
#     Experience: # map or dictionary
#       DevOps: 3 # number
#       AWS: 2
#       Docker: 1
#     RealProject: true #boolean
#   tasks:
#   - name: print variables
#     ansible.builtin.debug:
#       msg: "Course: {{Course}}, Tools covered: {{Tools}}, Experience is: {{Experience}}, is real project: {{RealProject}}"